---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: beryllos
# description will be included in the image's metadata
description: BeryllOS – a personalized Bazzite DX image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx
image-version: latest # latest is also supported if you want new updates ASAP
platforms:
  - linux/amd64

stages:
  - name: it87-extras
    from: ghcr.io/ublue-os/bazzite-dx
    modules:
      - type: copy
        src: kmod.*
        dest: /tmp/beryllos/

      - type: script
        scripts:
          - it87-extras.sh

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: bling
    install:
      - 1password

  - type: dnf
    repos:
      files:
        - https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
      keys:
        - https://download.sublimetext.com/sublimehq-rpm-pub.gpg
      copr:
        - atim/starship
    install:
      packages:
        #- repo: sublime-text
        #  packages:
        #    - sublime-text
        #    - sublime-merge
        - micro
        - starship

  # temporary workaround for failing Sublime apps install
  # see https://forum.sublimetext.com/t/installation-in-fedora-43-not-possible/77387
  - type: script
    snippets:
      - dnf5 download sublime-text sublime-merge
      - rpm -i --nodigest sublime-*.rpm
      - rm -f sublime-*.rpm

  - type: copy
    from: it87-extras
    src: /modules
    dest: /usr/lib/modules
  
  - type: initramfs

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
